let shopItemsData = [
  {
    id: "Cherry",
    name: "Пирог с вишней",
    price: 1300,
    desc: "слоеное тесто, вишня, сахар",
    img: "images/sweet1.webp",
  },
  {
    id: "Cranberry",
    name: "Пирог с клюквой",
    price: 1200,
    desc: "слоеное тесто, клюква, сахар",
    img: "images/sweet1.webp",
  },
  {
    id: "Apple",
    name: "Пирог с яблоками",
    price: 800,
    desc: "слоеное тесто, яблоки, корица, сахар",
    img: "images/apple.webp",
  },
  {
    id: "TurkeyPotato",
    name: "Пирог с индейкой и картофелем",
    price: 1000,
    desc: "слоеное тесто, индейка, картофель, лук",
    img: "images/pirog.webp",
  },
  {
    id: "TurkeyCabbge",
    name: "Пирог с индейкой и капустой",
    price: 1000,
    desc: "слоеное тесто, индейка, капуста, лук",
    img: "images/pirog3.webp",
  },
  {
    id: "ChikenMashrooms",
    name: "Пирог с курицей и грибами в сливках",
    price: 1400,
    desc: "слоеное тесто, курица, шампиньоны, лук, сливки",
    img: "images/pirog4.webp",
  },
  {
    id: "ChikenPotato",
    name: "Пирог с курицей и картофелем",
    price: 900,
    desc: "слоеное тесто, курица, картофель, лук",
    img: "images/pirog3.webp",
  },
  {
    id: "ChikenMashroomsPotato",
    name: "Пирог с курицей, грибами и картофелем",
    price: 1000,
    desc: "слоеное тесто, курица, шампиньоны, картофель, лук",
    img: "images/pirog4.webp",
  },
  {
    id: "ChikenCabbage",
    name: "Пирог с курицей и капустой",
    price: 900,
    desc: "слоеное тесто, курица, капуста, зелень, лук",
    img: "images/pirog.webp",
  },
  {
    id: "MeetPotato",
    name: "Пирог с рубленым мясом и картофелем",
    price: 850,
    desc: "слоеное тесто, рубленое мясо, картофель, лук",
    img: "images/pirog4.webp",
  },
  {
    id: "MeetEggs",
    name: "Пирог с рубленым мясом и яйцом",
    price: 1000,
    desc: "слоеное тесто, рубленое мясо, яйцо, лук, зелень",
    img: "images/pirog3.webp",
  },
  {
    id: "PorkPotato",
    name: "Пирог со свининой и картофелем",
    price: 950,
    desc: "слоеное тесто, свинина, картофель, лук",
    img: "images/pirog.webp",
  },
  {
    id: "CabbageEggs",
    name: "Пирог с капустой и яйцом",
    price: 700,
    desc: "слоеное тесто, капуста, яйцо, зелень, лук",
    img: "images/pirog.webp",
  },
  {
    id: "CabbageMashrooms",
    name: "Пирог с капустой и грибами",
    price: 950,
    desc: "слоеное тесто, капуста, шампиньоны, зелень, лук",
    img: "images/pirog4.webp",
  },
  {
    id: "PotatoMashroomsggs",
    name: "Пирог с картофелем и грибами",
    price: 950,
    desc: "слоеное тесто, картофель, шампиньоны, лук",
    img: "images/pirog3.webp",
  },
  {
    id: "RedFishPotato",
    name: "Пирог с горбушей и картофелем",
    price: 1300,
    desc: "слоеное тесто, горбуша, картофель, зелень, лук",
    img: "images/pirog3.webp",
  },
  {
    id: "RedFishRice",
    name: "Пирог с горбушей и рисом",
    price: 1300,
    desc: "слоеное тесто, горбуша, рис, зелень, лук",
    img: "images/pirog4.webp",
  },
  {
    id: "SalmonPotato",
    name: "Пирог с лососем и картофелем",
    price: 2300,
    desc: "слоеное тесто, лосось, картофель, зелень, лук",
    img: "images/pirog.webp",
  },
  {
    id: "SalmonRice",
    name: "Пирог с лососем и рисом",
    price: 2300,
    desc: "слоеное тесто, лосось, рис, зелень, лук",
    img: "images/pirog4.webp",
  },
  {
    id: "SudakPotato",
    name: "Пирог с судаком и картофелем",
    price: 1200,
    desc: "слоеное тесто, судак, картофель, зелень, лук",
    img: "images/pirog.webp",
  },
  {
    id: "SudakRice",
    name: "Пирог с судаком и рисом",
    price: 1200,
    desc: "слоеное тесто, судак, рис, зелень, лук",
    img: "images/pirog4.webp",
  },
];
